server:
  port: 8764
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
spring:
  application:
    name: turbine
security:
  basic:
    enabled: false
turbine:
  aggregator:
    cluster-config: default
  app-config: SERVICE-DEMO,CONSUMER-FEIGN,CONSUMER-RIBBON
  cluster-name-expression: new String("default")