server:
  port: 8802
spring:
  application:
    name: consumer-feign
  zipkin:
    base-url: http://localhost:8769
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
