server:
  port: 8801
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
spring:
  application:
    name: consumer-ribbon
  zipkin:
    base-url: http://localhost:8769